#!/usr/bin/env bash

# Extra tooling this project needs on top of the pretext-full image.
# Not generated by PreTeXt; safe to edit.

set -e

# installPandoc.sh may still be holding the apt locks.
while fuser /var/lib/dpkg/lock >/dev/null 2>&1 || fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
    echo "Waiting for apt-get to be free..."
    sleep 15
done

# gh drives the Actions workflows (`gh workflow run "Build and Deploy"`) and
# reads run status from inside the container; jq parses its JSON output. The
# same two packages are installed by .github/workflows/pretext-deploy.yml.
apt-get update
apt-get install -y --no-install-recommends gh jq

# The pretext-full image ships older pretext and prefig than this project pins,
# and the older prefig emits different ids in the generated SVGs. Installing
# requirements.txt makes a local `pretext generate` match CI, so the committed
# assets don't churn depending on where they were built.
pip install -r requirements.txt --break-system-packages

# Fetches the node and MathJax pieces prefig needs to typeset diagram labels.
# Without this, prefigure diagrams build without their labels.
prefig init
